image: node:18

pipelines:
  default:
    - parallel:
      - step:
          name: deploy-default
          script:
            - npm install && npm install -g wrangler && npm run build 
            - CLOUDFLARE_ACCOUNT_ID=$CF_ID CLOUDFLARE_API_TOKEN=$CF_TOKEN wrangler pages publish build --project-name=sms-doc --branch=main
      - step:
          name: deploy-alphasms-net
          script:
            - cp .env.alphasms.net .env
            - npm install && npm install -g wrangler && npm run build 
            - CLOUDFLARE_ACCOUNT_ID=$CF_ID CLOUDFLARE_API_TOKEN=$CF_TOKEN wrangler pages publish build --project-name=docs-alphasms-net --branch=main
      - step:
          name: deploy-alphasms-ua
          script:
            - cp .env.alphasms.ua .env
            - npm install && npm install -g wrangler && npm run build 
            - CLOUDFLARE_ACCOUNT_ID=$CF_ID CLOUDFLARE_API_TOKEN=$CF_TOKEN wrangler pages publish build --project-name=docs-alphasms-ua --branch=main
      - step:
          name: deploy-interconnect-solutions
          script:
            - cp .env.interconnect.solutions .env
            - npm install && npm install -g wrangler && npm run build 
            - CLOUDFLARE_ACCOUNT_ID=$CF_ID CLOUDFLARE_API_TOKEN=$CF_TOKEN wrangler pages publish build --project-name=docs-interconnect-solutions --branch=main
      - step:
          name: deploy-partner-alphasms-ua
          script:
            - cp .env.partner.alphasms.ua .env
            - npm install && npm install -g wrangler && npm run build 
            - CLOUDFLARE_ACCOUNT_ID=$CF_ID CLOUDFLARE_API_TOKEN=$CF_TOKEN wrangler pages publish build --project-name=partner-alphasms-ua --branch=main
      - step:
          name: deploy-partner-interconnect-solutions
          script:
            - cp .env.partner.interconnect.solutions .env
            - npm install && npm install -g wrangler && npm run build 
            - CLOUDFLARE_ACCOUNT_ID=$CF_ID CLOUDFLARE_API_TOKEN=$CF_TOKEN wrangler pages publish build --project-name=partner-interconnect-solutions --branch=main
      - step:
          name: deploy-blackbox-business
          script:
            - cp .env.blackbox.business .env
            - npm install && npm install -g wrangler && npm run build 
            - CLOUDFLARE_ACCOUNT_ID=$CF_ID CLOUDFLARE_API_TOKEN=$CF_TOKEN wrangler pages publish build --project-name=blackbox-business --branch=main